@baseUrl = https://www.example.com

###
#  Test GET Endpoint
GET {{baseUrl}}/test

###
#  Test POST Endpoint
POST {{baseUrl}}/echo
{
	"Status": "HELLO"
}

###
# @login Test POST Auth Endpoint
POST {{baseUrl}}/login
{
	"Status": "HELLO"
}

@authToken = {{login.response.body.AuthToken}}

###
#  Test GET Endpoint with route param
GET {{baseUrl}}/param/:value

###
#  Test PUT Endpoint with route param
PUT {{baseUrl}}/param/:value
{
	"Status": "HELLO"
}

