@baseUrl = https://www.example.com

###
#Test GET Endpoint
GET {{baseUrl}}/test
Content-Type: application/json

###
#Test POST Endpoint
POST {{baseUrl}}/echo
Content-Type: application/json
Token: 123
{
	"Status": "HELLO"
}

###
#Test GET Endpoint with route param
GET {{baseUrl}}/param/:value
Content-Type: application/json

###
#Test PUT Endpoint with route param
PUT {{baseUrl}}/param/:value
Content-Type: application/json
{
	"Status": "HELLO"
}

